export const C = {
  bg: "#0c0c0e",
  surface: "#131316",
  elevated: "#1a1a1f",
  border: "#252530",
  borderLight: "#2e2e3a",
  accent: "#3b82f6",
  accentDim: "#2563eb",
  green: "#4ade80",
  red: "#f87171",
  yellow: "#fbbf24",
  textPrimary: "#f0f0f5",
  textSecondary: "#8888a0",
  textMuted: "#55556a",
};

export const S = {
  app: { background: C.bg, minHeight: "100vh", fontFamily: "'Roboto', 'Arial', sans-serif", color: C.textPrimary },
  header: { background: C.surface, borderBottom: `1px solid ${C.border}`, padding: "14px 20px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  nav: { display: "flex", background: C.surface, borderBottom: `1px solid ${C.border}`, overflowX: "auto" },
  navBtn: (active) => ({ padding: "12px 16px", background: "none", border: "none", borderBottom: active ? `2px solid ${C.accent}` : "2px solid transparent", color: active ? C.accent : C.textSecondary, cursor: "pointer", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", fontFamily: "inherit", whiteSpace: "nowrap", transition: "all 0.15s" }),
  content: { padding: "20px", maxWidth: 900, margin: "0 auto" },
  card: { background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: "16px 20px", marginBottom: 12 },
  cardTitle: { fontSize: 11, color: C.accent, letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 14, fontWeight: 500 },
  input: { width: "100%", background: C.elevated, border: `1px solid ${C.border}`, borderRadius: 6, padding: "9px 12px", color: C.textPrimary, fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box", transition: "border-color 0.15s" },
  label: { display: "block", fontSize: 10, color: C.textMuted, marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.1em" },
  btnPrimary: { background: C.accent, border: "none", borderRadius: 6, padding: "10px 20px", color: "#fff", fontSize: 12, fontWeight: 600, letterSpacing: "0.1em", cursor: "pointer", fontFamily: "inherit", textTransform: "uppercase" },
  btnSecondary: { background: C.elevated, border: `1px solid ${C.border}`, borderRadius: 6, padding: "10px 20px", color: C.textSecondary, fontSize: 12, fontWeight: 500, letterSpacing: "0.1em", cursor: "pointer", fontFamily: "inherit", textTransform: "uppercase" },
  btnDanger: { background: "none", border: `1px solid ${C.red}`, borderRadius: 6, padding: "6px 14px", color: C.red, fontSize: 11, cursor: "pointer", fontFamily: "inherit" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 },
  stat: { background: C.elevated, border: `1px solid ${C.border}`, borderRadius: 8, padding: "14px 16px" },
  statLabel: { fontSize: 10, color: C.textMuted, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 4 },
  statValue: { fontSize: 22, fontWeight: 600, color: C.textPrimary },
  tag: (color) => ({ display: "inline-block", background: color + "22", color: color, border: `1px solid ${color}44`, borderRadius: 4, padding: "2px 8px", fontSize: 10, letterSpacing: "0.08em" }),
  row: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 0", borderBottom: `1px solid ${C.border}` },
  sectionHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
};
